name: CI
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

permissions:
  contents: read

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install ReFrame
        run: |
          uv tool install https://github.com/reframe-hpc/reframe.git

      - id: set-matrix
        run: |
          echo "::set-output name=matrix::$(reframe -P num_nodes=1,2,4 -c tests.py --describe | jq -c '{include: [.[] | {name, hashcode}]}')"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo ${{ matrix.name }}
    - run: echo ${{ matrix.hashcode }}
